# permissions for end users to view applications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: application-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: clusterops-operator
    app.kubernetes.io/part-of: clusterops-operator
    app.kubernetes.io/managed-by: kustomize
  name: application-viewer-role
rules:
- apiGroups:
  - apps.clusterops.io
  resources:
  - applications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.clusterops.io
  resources:
  - applications/status
  verbs:
  - get
