---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployment
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployment/status
  verbs:
  - get
- apiGroups:
  - apps.clusterops.io
  resources:
  - applications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.clusterops.io
  resources:
  - applications/finalizers
  verbs:
  - update
- apiGroups:
  - apps.clusterops.io
  resources:
  - applications/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - service
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - service/status
  verbs:
  - get
