apiVersion: apps.clusterops.io/v1
kind: Application
metadata:
  labels:
    app.kubernetes.io/name: application
    app.kubernetes.io/instance: application-sample
    app.kubernetes.io/part-of: clusterops-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: clusterops-operator
  name: application-sample
spec:
  # TODO(user): Add fields here
